services:
  - type: web
    name: InYourLane
    env: node
    branch: inprogress
    buildCommand: npm run render-seed
    startCommand: npm start
    envVars:
      - key: DB_URL
        sync: false
