services:
  - type: web
    name: InYourLane
    env: node
    branch: main
    buildCommand: npm run render-seed
    startCommand: npm start
    envVars:
      - key: DB_URL
        sync: false # keeps the existing DB_URL intact
